### ISSUE TITLE
the code is not endless in my env, why?

### ISSUE THREAD

**Issue by johncming** [empijei/gotalks#1]
```golang
    go func() {
        for i = 0; i <= 255; i++ {
        }
    }()
    fmt.Println("Dropping mic")
    // Yield execution to force executing other goroutines
    runtime.Gosched()
    runtime.GC()
    fmt.Println("Done")
```

go version go1.11 darwin/amd64

**Comment by empijei** [comment]
Thanks for reporting this, just let me ask a couple of questions:

- Are you running this on your mac or inside the play/talk env?

- Could you please try to clone this repo, change directory to `gophercon/gc` and run `go build; ./gc` ? (or anyhow run the compiled code on your machine)

I'm asking this because the runtime is different when running in the `play` env, [here is an interesting explaination on why](https://blog.golang.org/playground).

**Comment by johncming** [comment]
> Are you running this on your mac or inside the play/talk env?

Yes, on my mac. I also try linux vm env.

> Could you please try to clone this repo, change directory to gophercon/gc and run go build; ./gc ? (or anyhow run the compiled code on your machine)

complete code: 

```golang
package main

import (
	"fmt"
	"runtime"
)

func main() {
	var i int  // byte type in your code
	go func() {
		for i = 0; i <= 255; i++ {
		}
	}()
	fmt.Println("Dropping mic")
	// Yield execution to force executing other goroutines
	runtime.Gosched()
	runtime.GC()
	fmt.Println("Done")
}
```

**Comment by empijei** [comment]
Output of `go env` and `go version`? I'm trying to reproduce this but it always runs an endless loop on my environment.

**Comment by johncming** [comment]
## go env

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ming/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/ming/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/th/thpfz5y97pn2ccnp7p_rjgq00000gn/T/go-build201725632=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

## go version

go version go1.11 darwin/amd64

## output

```shell
Dropping mic
Done
```

**Comment by empijei** [comment]
Okay, thanks for the data, the problem is that you changed the type to int, so the loop ends, and the process ends with it. This works only if you use and endless or very long loop. If you want to use an int to see that it lasts longer just increase the limit from 255 to math.MaxInt64 and you will see it takes time before it can successfully terminate.

With byte it overflows every 255 iterations so the loop never ends.

**Comment by johncming** [comment]
@empijei ok, thanks
